/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 An Orange.glb -T -t -o AnOrange.tsx 
Files: An Orange.glb [24.83KB] > /Users/christopherneale/projects/models/An Orange-transformed.glb [3.35KB] (87%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group879198542: THREE.Mesh
    group589766384: THREE.Mesh
  }
  materials: {
    mat13: THREE.MeshStandardMaterial
    mat9: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/An Orange-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={50}>
      <mesh geometry={nodes.group879198542.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group589766384.geometry} material={materials.mat9} />
    </group>
  )
}

useGLTF.preload('/models/An Orange-transformed.glb')
