/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Banana Bundle.glb -T -t -o BananaBundle.tsx 
Files: Banana Bundle.glb [27.87KB] > /Users/christopherneale/projects/models/Banana Bundle-transformed.glb [5.02KB] (82%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Banana2_1: THREE.Mesh
    Banana2_2: THREE.Mesh
  }
  materials: {
    Banana: THREE.MeshStandardMaterial
    Banana1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Banana Bundle-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-2.532, 0.789, -0.582]} rotation={[0.356, -0.849, 0]} scale={250}>
        <mesh geometry={nodes.Banana2_1.geometry} material={materials.Banana} />
        <mesh geometry={nodes.Banana2_2.geometry} material={materials.Banana1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Banana Bundle-transformed.glb')
