/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Bomb.glb -T -t -o Bomb.tsx 
Files: Bomb.glb [29.2KB] > /Users/christopherneale/projects/models/Bomb-transformed.glb [7.92KB] (73%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Prop_Bomb: THREE.Mesh
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Bomb-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Prop_Bomb.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Bomb-transformed.glb')
