/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Bread Slice.glb -o ./src/weapons-breadslice.tsx --transform --types 
Files: ../Models/Bread Slice.glb [28.88KB] > /Users/christopherneale/projects/shooter/ddbh/src/Bread Slice-transformed.glb [10.4KB] (64%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    bread_slice: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function ItemBreadSlice(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/BreadSlice-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bread_slice.geometry} material={materials.tiny_treats_1} scale={150} />
    </group>
  )
}

useGLTF.preload('/models/BreadSlice-transformed.glb')
