/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Bread.glb -o ./src/weapons-bread.tsx --transform --types 
Files: ../Models/Bread.glb [33.92KB] > /Users/christopherneale/projects/shooter/ddbh/src/Bread-transformed.glb [11.56KB] (66%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    bread: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function WeaponsBread(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Bread-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bread.geometry} material={materials.tiny_treats_1} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Bread-transformed.glb')
