/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Bread Roll.glb -o ./src/weapons-breadroll.tsx --transform --types 
Files: ../Models/Bread Roll.glb [30.93KB] > /Users/christopherneale/projects/shooter/ddbh/src/Bread Roll-transformed.glb [10.98KB] (65%)
*/

import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    bread_roll: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function WeaponsBreadRoll(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/BreadRoll-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bread_roll.geometry} material={materials.tiny_treats_1} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/BreadRoll-transformed.glb')
