/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Cake Birthday Slice.glb -o ./src/weapons-cakebirthdayslice.tsx --transform --types 
Files: ../Models/Cake Birthday Slice.glb [40.38KB] > /Users/christopherneale/projects/shooter/ddbh/src/Cake Birthday Slice-transformed.glb [12.15KB] (70%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    cake_birthday_slice: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function WeaponsCakeBirthdaySlice(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/CakeBirthdaySlice-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cake_birthday_slice.geometry} material={materials.tiny_treats_1} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/CakeBirthdaySlice-transformed.glb')
