/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Cake Chocolate Slice.glb -o ./src/weapons-cakechocolateslice.tsx --transform --types 
Files: ../Models/Cake Chocolate Slice.glb [36.38KB] > /Users/christopherneale/projects/shooter/ddbh/src/Cake Chocolate Slice-transformed.glb [11.7KB] (68%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    cake_chocolate_slice: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function ItemCakeChocolateSlice(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/CakeChocolateSlice-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cake_chocolate_slice.geometry} material={materials.tiny_treats_1} scale={120} />
    </group>
  )
}

useGLTF.preload('/models/CakeChocolateSlice-transformed.glb')
