/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cash Stack.glb -T -t -o CashStack.tsx 
Files: Cash Stack.glb [160.91KB] > /Users/christopherneale/projects/models/Cash Stack-transformed.glb [15.12KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cash3_1: THREE.Mesh
    Cash3_2: THREE.Mesh
    Cash3_3: THREE.Mesh
  }
  materials: {
    Wrap: THREE.MeshStandardMaterial
    Green_Tone2: THREE.MeshStandardMaterial
    Green_Tone1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Cash Stack-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.009, 0.085, -0.202]} rotation={[-Math.PI / 2, 0, 0]} scale={13}>
        <mesh geometry={nodes.Cash3_1.geometry} material={materials.Wrap} />
        <mesh geometry={nodes.Cash3_2.geometry} material={materials.Green_Tone2} />
        <mesh geometry={nodes.Cash3_3.geometry} material={materials.Green_Tone1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Cash Stack-transformed.glb')
