/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cherry.glb -T -t -o Cherry.tsx 
Files: Cherry.glb [231.21KB] > /Users/christopherneale/projects/models/Cherry-transformed.glb [13.38KB] (94%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere001: THREE.Mesh
    Cylinder001: THREE.Mesh
  }
  materials: {
    _crayfishdiffuse: THREE.MeshStandardMaterial
    ['02___Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Cherry-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.00002}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials._crayfishdiffuse} scale={0.1} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['02___Default']}  scale={0.1} />
    </group>
  )
}

useGLTF.preload('/models/Cherry-transformed.glb')
