/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Chest Gold.glb -T -t -o ChestGold.tsx 
Files: Chest Gold.glb [307.68KB] > /Users/christopherneale/projects/models/Chest Gold-transformed.glb [32.97KB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Prop_Chest_Gold: THREE.Mesh
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Chest Gold-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Prop_Chest_Gold.geometry} material={materials.Atlas} scale={60} />
    </group>
  )
}

useGLTF.preload('/models/Chest Gold-transformed.glb')
