/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Coin.glb -T -t -o Coin.tsx 
Files: Coin.glb [22.3KB] > /Users/christopherneale/projects/models/Coin-transformed.glb [3.08KB] (86%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Coin: THREE.Mesh
  }
  materials: {
    Gold: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Coin-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Coin.geometry} material={materials.Gold} rotation={[-Math.PI / 2, 0, 0]} scale={70} />
    </group>
  )
}

useGLTF.preload('/models/Coin-transformed.glb')
