/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Croissant.glb -o ./src/weapons-croisssant.tsx --transform --types 
Files: ../Models/Croissant.glb [33.37KB] > /Users/christopherneale/projects/shooter/ddbh/src/Croissant-transformed.glb [11.63KB] (65%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    croissant: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function WeaponsCroissant(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Croissant-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.croissant.geometry} material={materials.tiny_treats_1} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Croissant-transformed.glb')
