/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Crown.glb -T -t -o Crown.tsx 
Files: Crown.glb [47.62KB] > /Users/christopherneale/projects/models/Crown-transformed.glb [6.15KB] (87%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Crown2_1: THREE.Mesh
    Crown2_2: THREE.Mesh
  }
  materials: {
    Gold: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Crown-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Crown2_1.geometry} material={materials.Gold} />
        <mesh geometry={nodes.Crown2_2.geometry} material={materials.Red} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Crown-transformed.glb')
