/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Cupcake.glb -o ./src/weapons-cupcake.tsx --transform --types 
Files: ../Models/Cupcake.glb [49.65KB] > /Users/christopherneale/projects/shooter/ddbh/src/Cupcake-transformed.glb [14.2KB] (71%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    cupcake: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function WeaponsCupcake(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Cupcake-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cupcake.geometry} material={materials.tiny_treats_1} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Cupcake-transformed.glb')
