/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Donut.glb -o ./src/weapons-donut.tsx --transform --types 
Files: ../Models/Donut.glb [31.03KB] > /Users/christopherneale/projects/shooter/ddbh/src/Donut-transformed.glb [11.14KB] (64%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    donut: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function ItemDonut(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Donut-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.donut.geometry} material={materials.tiny_treats_1} scale={200} />
    </group>
  )
}

useGLTF.preload('/models/Donut-transformed.glb')
