/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gold Bars.glb -T -t -o GoldBars.tsx 
Files: Gold Bars.glb [27.58KB] > /Users/christopherneale/projects/models/Gold Bars-transformed.glb [2.77KB] (90%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Gold Bars-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.727, 0.495, 0.724]} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
    </group>
  )
}

useGLTF.preload('/models/Gold Bars-transformed.glb')
