/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gold.glb -T -t -o Gold.tsx 
Files: Gold.glb [5.24KB] > /Users/christopherneale/projects/models/Gold-transformed.glb [1.62KB] (69%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Gold_Q: THREE.Mesh
  }
  materials: {
    phong1SG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Gold-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gold_Q.geometry} material={materials.phong1SG} />
    </group>
  )
}

useGLTF.preload('/models/Gold-transformed.glb')
