/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gold Bag.glb -T -t -o GoldBag.tsx 
Files: Gold Bag.glb [165.21KB] > /Users/christopherneale/projects/models/Gold Bag-transformed.glb [20.54KB] (88%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Prop_GoldBag: THREE.Mesh
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Gold Bag-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Prop_GoldBag.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Gold Bag-transformed.glb')
