/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Grapes.glb -T -t -o Grapes.tsx 
Files: Grapes.glb [156.17KB] > /Users/christopherneale/projects/models/Grapes-transformed.glb [13.04KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Icosphere015_Icosphere018-Mesh']: THREE.Mesh
    ['Icosphere015_Icosphere018-Mesh_1']: THREE.Mesh
  }
  materials: {
    ['4CAF50']: THREE.MeshStandardMaterial
    ['673AB7']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Grapes-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.125}>
      <mesh geometry={nodes['Icosphere015_Icosphere018-Mesh'].geometry} material={materials['4CAF50']} />
      <mesh geometry={nodes['Icosphere015_Icosphere018-Mesh_1'].geometry} material={materials['673AB7']} />
    </group>
  )
}

useGLTF.preload('/models/Grapes-transformed.glb')
