/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Lemon.glb -T -t -o Lemon.tsx 
Files: Lemon.glb [19.7KB] > /Users/christopherneale/projects/models/Lemon-transformed.glb [3.1KB] (84%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pSphere3_1: THREE.Mesh
    pSphere3_1_1: THREE.Mesh
  }
  materials: {
    blinn1SG: THREE.MeshStandardMaterial
    blinn2SG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Lemon-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.002}>
      <mesh geometry={nodes.pSphere3_1.geometry} material={materials.blinn1SG} />
      <mesh geometry={nodes.pSphere3_1_1.geometry} material={materials.blinn2SG} />
    </group>
  )
}

useGLTF.preload('/models/Lemon-transformed.glb')
