/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Mushroom.glb -T -t -o Mushroom.tsx 
Files: Mushroom.glb [10.29KB] > /Users/christopherneale/projects/models/Mushroom-transformed.glb [2.98KB] (71%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mushroom_1: THREE.Mesh
    Mushroom_2: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    LightRed: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Mushroom-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Mushroom_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Mushroom_2.geometry} material={materials.LightRed} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Mushroom-transformed.glb')
