/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../Models/Pie Cherry.glb -o ./src/weapons-piecherry.tsx --transform --types 
Files: ../Models/Pie Cherry.glb [42.98KB] > /Users/christopherneale/projects/shooter/ddbh/src/Pie Cherry-transformed.glb [13.91KB] (68%)
*/

import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    pie_cherry: Mesh
  }
  materials: {
    tiny_treats_1: MeshStandardMaterial
  }
}

export function WeaponsPieCherry(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/PieCherry-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pie_cherry.geometry} material={materials.tiny_treats_1} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/PieCherry-transformed.glb')
